[versions]
maven-settings-builder = "3.9.6"
plexus-cipher = "2.0"
plexus-sec-dispatcher = "2.0"
junit-jupiter = "5.12.1"

[libraries]
maven-settings-builder = { module = "org.apache.maven:maven-settings-builder", version.ref = "maven-settings-builder" }
plexus-cipher = { module = "org.codehaus.plexus:plexus-cipher", version.ref = "plexus-cipher" }
plexus-sec-dispatcher = { module = "org.codehaus.plexus:plexus-sec-dispatcher", version.ref = "plexus-sec-dispatcher" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
